# Site settings
title: True Agile |
description: Scrum Links
# keywords:
# author:
baseurl: "https://iamjackreed.github.io" # the subpath of your site, e.g. /blog/
url: "/mod" # the base hostname & protocol for your site
